Build the User Interface.
martinoywa/numbers-tutor pull request #21
Opened 2020-12-08 06:57 UTC by KelynPNjeri

This PR contains the code to the initial `landing page`, `voice input page`, `write number page`. To test the code, you need to clone the application and run **index.html** so that you can naviggate through the UI. Additional feature are currently a **WIP**.

2020-12-08 06:57 UTC, martinoywa commented
Task linked: [CU-apyazp Build the User Interface](https://app.clickup.com/t/apyazp)

2020-12-08 10:29 UTC, martinoywa requested changes
Most things seem to be okay, but the design pattern followed is not modular as per 
this design doc https://app.clickup.com/4522322/v/dc/4a0aj-113/4a0aj-29

2020-12-08 10:29 UTC, martinoywa commented on index.html
> +    <link rel="stylesheet" href="assets/css/style.css">
This CSS doesn't seem to have been applied to the index file.

2020-12-09 08:48 UTC, Mindo-Joseph submitted a review, later dismissed
Soo I had not run the code from the server, 😨 , the CSS was not loading ⚠️ , structure the code to look like below
![Screenshot from 2020-12-09 14-19-15](https://user-images.githubusercontent.com/47358442/101623611-c1894100-3a29-11eb-8736-4513e3c66959.png)

2020-12-09 17:46 UTC, martinoywa commented
Yeah, but I believe it's being worked on @KelynPNjeri?

2020-12-09 19:06 UTC, Mindo-Joseph commented
Yeah but I also did it for the tests, will make a PR soon 😎

2020-12-10 09:22 UTC, martinoywa commented
Perfect! 

 

From: Joseph Mindo <notifications@github.com> 
Sent: Wednesday, December 9, 2020 10:07 PM
To: martinoywa/numbers-tutor <numbers-tutor@noreply.github.com>
Cc: Martin Oywa <martinoywa2@gmail.com>; Review requested <review_requested@noreply.github.com>
Subject: Re: [martinoywa/numbers-tutor] Build the User Interface. (#21)

 

Yeah but I also did it for the tests, will make a PR soon 😎

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub <https://github.com/martinoywa/numbers-tutor/pull/21#issuecomment-741984924> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AIAEB3ML3SEVAGA33MPTXRDST7DF5ANCNFSM4URQ7YYQ> .  <https://github.com/notifications/beacon/AIAEB3MYILQMZ3SY3GRURO3ST7DF5A5CNFSM4URQ7YY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFQ44VHA.gif>

2020-12-16 07:36 UTC, martinoywa approved these changes

2020-12-16 07:52 UTC, merged