Image recognition module [SVHN]
martinoywa/numbers-tutor pull request #28
Opened 2020-12-20 12:43 UTC by martinoywa

This PR contains code for the updated image recognition module.
Main changes are an `updated model`  which now can `recognize multiple numbers` from a single image. 
This is due to us only using one canvas to draw on in the write page.

Check tests and updated module files for more details.

2020-12-20 12:43 UTC, martinoywa commented
Task linked: [CU-apyem5 Image recognition module](https://app.clickup.com/t/apyem5)

2020-12-20 13:13 UTC, martinoywa commented
**Note:** Tests will not run in workflow because of how git-lfs handles large files. Technically the model doesn't exist to be used for inferencing. You'll need to run the tests locally.

2020-12-23 07:23 UTC, KelynPNjeri requested changes
Fix the one test, apart from that all is great.

2020-12-23 07:23 UTC, KelynPNjeri commented on app/ai/write/tests/test_write.py
>      def test_model_loading(self):
Ensure this test passes.

2020-12-23 10:24 UTC, KelynPNjeri approved these changes
Everything seems OK. Merge.

2020-12-24 11:21 UTC, martinoywa commented
> Everything seems OK. Merge.

Perfect!

2020-12-24 11:21 UTC, merged